In [2]:
import pandas as pd

# In real time data we will have datas like table format or key and value pairs which cannot be handled using numpy so we use pandas

Exploratory Data analysis

In [22]:
data = {
    "Student_ID": [101, 102, 103, 104, 105,106,107],
    "Name": ["Arun", "Priya", "Karthik", "Meena", "Rahul","Rithi","Nisha"],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT",None,None],
    "Attendance": [82, 91, 76, 68, 88, 90, 89],
    "Python": [85, 92, 76, 65, 88, None, 90],
    "SQL": [78, 88, 82, 70, 91,45,34],
    "Excel": [90, 95, 80, 72, 86,45,78]
}

df=pd.DataFrame(data) # Dataframe
print(df)

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82    85.0   78     90
1         102    Priya         IT          91    92.0   88     95
2         103  Karthik        CSE          76    76.0   82     80
3         104    Meena        ECE          68    65.0   70     72
4         105    Rahul         IT          88    88.0   91     86
5         106    Rithi        NaN          90     NaN   45     45
6         107    Nisha        NaN          89    90.0   34     78

In [ ]:
df1=pd.Series(data)  # To print series
print(df1)

Student_ID               [101, 102, 103, 104, 105]
Name          [Arun, Priya, Karthik, Meena, Rahul]
Department                 [CSE, IT, CSE, ECE, IT]
Attendance                    [82, 91, 76, 68, 88]
Python                        [85, 92, 76, 65, 88]
SQL                           [78, 88, 82, 70, 91]
Excel                         [90, 95, 80, 72, 86]
dtype: object

In [ ]:
print(df.head) # 1.to print first 5 records  2. Default 5 we can list based on our need

<bound method NDFrame.head of    Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86>

In [ ]:
df.tail()  # 1.to print last 5 records  2. Default 5 we can list based on our need

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86

In [ ]:
df.sample(3)  # it prints randomly based on the requirements

   Student_ID   Name Department  Attendance  Python  SQL  Excel
1         102  Priya         IT          91      92   88     95
3         104  Meena        ECE          68      65   70     72
4         105  Rahul         IT          88      88   91     86

In [ ]:
df.shape # to print the number of rows and columns

(5, 7)

In [ ]:
df.columns  # to print the columns names

Index(['Student_ID', 'Name', 'Department', 'Attendance', 'Python', 'SQL',
       'Excel'],
      dtype='str')

In [ ]:
df.info() # it gives all the details

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      str
 2   Department  5 non-null      str
 3   Attendance  5 non-null      int64
 4   Python      5 non-null      int64
 5   SQL         5 non-null      int64
 6   Excel       5 non-null      int64
dtypes: int64(5), str(2)
memory usage: 451.0 bytes

In [19]:
df.describe()  # it will give all statistics summary which includes count,mean,std,min,max,percentiles

       Student_ID  Attendance     Python        SQL      Excel
count    7.000000    7.000000   6.000000   7.000000   7.000000
mean   104.000000   83.428571  82.666667  69.714286  78.000000
std      2.160247    8.638232  10.308572  21.959920  16.462078
min    101.000000   68.000000  65.000000  34.000000  45.000000
25%    102.500000   79.000000  78.250000  57.500000  75.000000
50%    104.000000   88.000000  86.500000  78.000000  80.000000
75%    105.500000   89.500000  89.500000  85.000000  88.000000
max    107.000000   91.000000  92.000000  91.000000  95.000000

In [ ]:
df["Python"].dtype  # To access the data 
# Here we are not accesing the eac mark here when i call Python column name it gives the datatype of all data . this data vectorization

dtype('float64')

In [ ]:
df[["Name","Department","Python"]] # To access multiple columns

      Name Department  Python
0     Arun        CSE    85.0
1    Priya         IT    92.0
2  Karthik        CSE    76.0
3    Meena        ECE    65.0
4    Rahul         IT    88.0
5    Rithi        NaN     NaN
6    Nisha        NaN    90.0

In [ ]:
# Indexing using iloc

# It access using indexing value

print(df.iloc[0]) # to access 1st row
print(df.iloc[0,3]) # To access any value inside that particular row

print(df.iloc[[0,2,3]]) # To access two or more columns columns

print(df[["Name","Department"]].iloc[0:4]) 



# Indexing using lebels and index
df.loc[0,["Name"]]

(0       Arun
 1      Priya
 2    Karthik
 3      Meena
 4      Rahul
 5      Rithi
 6      Nisha
 Name: Name, dtype: str,
 0     True
 1     True
 2     True
 3    False
 4     True
 5     True
 6     True
 Name: Attendance, dtype: bool)

Filtering

In [ ]:
# # student rows whose rows > 75
cond=df[df["Attendance"]>=75]
print(cond.Name)

# Find students whose attendance is atleast 75 and python mark is atleast 80
print(df.loc[(df["Attendance"]>=75) & (df["Python"]>=80)])

# Calculate the avg of python,sql and excel
# print((df[["Python","SQL","Excel"]].sum())/3)

# Calculate the avg of python,sql and excel for each person
(df["Python"]+df["SQL"]+df["Excel"])//3

0       Arun
1      Priya
2    Karthik
4      Rahul
5      Rithi
6      Nisha
Name: Name, dtype: str
   Student_ID   Name Department  Attendance  Python  SQL  Excel
0         101   Arun        CSE          82    85.0   78     90
1         102  Priya         IT          91    92.0   88     95
4         105  Rahul         IT          88    88.0   91     86
6         107  Nisha        NaN          89    90.0   34     78

0    84.333333
1    91.666667
2    79.333333
3    69.000000
4    88.333333
5          NaN
6    67.333333
dtype: float64

Data Manipulation

In [ ]:
# To add a column
df["Average"]=(df["Python"]+df["SQL"]+df["Excel"])//3
df

   Student_ID     Name Department  Attendance  Python  SQL  Excel  Average
0         101     Arun        CSE          82    85.0   78     90     84.0
1         102    Priya         IT          91    92.0   88     95     91.0
2         103  Karthik        CSE          76    76.0   82     80     79.0
3         104    Meena        ECE          68    65.0   70     72     69.0
4         105    Rahul         IT          88    88.0   91     86     88.0
5         106    Rithi        NaN          90     NaN   45     45      NaN
6         107    Nisha        NaN          89    90.0   34     78     67.0

In [72]:
# Add a column when the average is greater than 50 pass else fail
df["Results"]=df["Average"].apply(lambda x: "Pass" if x>=50 else "Fail")
df

,Student_ID,Name,Department,Attendance,Python,SQL,Excel,Average,Results
0,101,Arun,CSE,82,85.0,78,90,84.0,Pass
1,102,Priya,IT,91,92.0,88,95,91.0,Pass
2,103,Karthik,CSE,76,76.0,82,80,79.0,Pass
3,104,Meena,ECE,68,65.0,70,72,69.0,Pass
4,105,Rahul,IT,88,88.0,91,86,88.0,Pass
5,106,Rithi,NaN,90,NaN,45,45,NaN,Fail
6,107,Nisha,NaN,89,90.0,34,78,67.0,Pass

Sort

In [74]:
# Ascending order
df.sort_values(by="Average") # ascending default

# Descending order
df.sort_values(by="Average",ascending=False)

,Student_ID,Name,Department,Attendance,Python,SQL,Excel,Average,Results
1,102,Priya,IT,91,92.0,88,95,91.0,Pass
4,105,Rahul,IT,88,88.0,91,86,88.0,Pass
0,101,Arun,CSE,82,85.0,78,90,84.0,Pass
2,103,Karthik,CSE,76,76.0,82,80,79.0,Pass
3,104,Meena,ECE,68,65.0,70,72,69.0,Pass
6,107,Nisha,NaN,89,90.0,34,78,67.0,Pass
5,106,Rithi,NaN,90,NaN,45,45,NaN,Fail

Group by

In [75]:
# what is the avg python mark for each department
df.groupby("Department")["Python"].mean()

Department
CSE    80.5
ECE    65.0
IT     90.0
Name: Python, dtype: float64

In [76]:
# Number of students per department
df.groupby("Department")["Student_ID"].count()

Department
CSE    2
ECE    1
IT     2
Name: Student_ID, dtype: int64

In [77]:
# Highest python mark by department
df.groupby("Department")["Python"].max()

Department
CSE    85.0
ECE    65.0
IT     92.0
Name: Python, dtype: float64

Group by with multiple metrics

In [80]:
df.groupby("Department").agg({
    "Student_ID":"count",
    "Python":"mean",
    "Excel":"mean",
    "SQL":"mean",
    "Attendance":"mean"
    })

            Student_ID  Python  Excel   SQL  Attendance
Department
CSE                  2    80.5   85.0  80.0        79.0
ECE                  1    65.0   72.0  70.0        68.0
IT                   2    90.0   90.5  89.5        89.5

Load file

In [3]:
exc=pd.read_csv(r"D:\Rithiha\Python\Projects\Src\Foundation\Python libraries\dim_plants.csv")
exc.columns

Index(['plant_id', 'plant_name', 'location_city', 'location_country',
       'established_date', 'capacity_mwh'],
      dtype='str')